### PR TITLE
added lines argument to add_xml_location

### PR DESCRIPTION
**Pull request by johannesWen**
**Description**

Added a "lines" argumnet to the add_xml_location function. This is useful to find the XML element easier in the whole opendrive file.

Usage can be seen in https://github.com/asam-ev/qc-opendrive/pull/124

**Main changes**

1. Added lines attribute to class XMLLocationType
2. Added lines argument to add_xml_location()
3. Test update

**How was the PR tested?**

1. Pytests successful

### CODE REVIEW

**Comment by andreaskern74** [comment]
Hey @johannesWen,

Thanks for contributing to this project!

I think your use case is that it is easier to find the issue in the source file as a human, because the xpath is not really good readable. See also https://github.com/asam-ev/qc-opendrive/issues/121 regarding this topic.

If you want to see the line numbers in the source code, there are three things to know:
* Result file: The right format is to add a `<FileLocation/>` to the issue. Then the source code view in the ReportGUI will directly move to that location when clicking on it
* Automatic generation: The  `<FileLocation/>` is automatically generated from the xpath when using the Result Pooling (C++ component)
* Framework goes Python: The whole framework moves towards Python. See https://github.com/asam-ev/qc-framework/pull/191. The idea is also to provide the ResultPooling in Python, so that it is not necessary to compile the components, except you want to use the GUI. @MatteoRagni FYI

Nevertheless, I totally understand that people just want to use qc-opendrive without the pooling/reporting . Probably it's possible to adapt this PR that it creates `<FileLocation/>`. Then it is still compliant to the specification.

**Comment by johannesWen** [comment]
Hi @andreaskern74,

yes, this would be exactly the use case, to use qc-opendrive as a library without the Report GUI. 
I will see, how I can adapt the PR.

**Comment by johannesWen** [comment]
Hi @andreaskern74,

I just added an add_file_location() to all checks in qc-opendrive (https://github.com/asam-ev/qc-opendrive/pull/124/commits/dae5d1fd1f823d1162bbd049bdc79ff5f351ccea).
I'm not sure if this is an appropriate solution, but it doesn't require a change of the specification.

**Comment by johannesWen** [comment]
Resolved by PR https://github.com/asam-ev/qc-opendrive/pull/124

**Pull request closed without merging**
